sudo: false
dist: trusty
language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache
notifications:
  email: false
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - re2c
matrix:
    include:
    - name: "7.0 master"
      env: BASE=7.0  STATIC=shared

    - name: "3.16 master"
      env: BASE=3.16  STATIC=shared
    
    - name: "3.15 master"
      env: BASE=3.15  STATIC=shared
        
    - name: "3.14 master"
      env: BASE=3.14  STATIC=shared
        
    - name: "Windows Shared"
      env: BASE=3.16  STATIC=shared CMPLR=clang WINE=32
        
    - name: "Windows Static"
      env: BASE=3.16  STATIC=static CMPLR=clang WINE=32
    

        
before_install: chmod +x ./.ci/assemble_synApps.sh

install: ./.ci/assemble_synApps.sh

script: 
    # Build the module
    - make
 
